server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot-001?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update